theme: jekyll-theme-slate
title: Welcome to the Ilona Kosińska's homepage.
description: Contact info that allows users to get in contact with me if they experience problems, desire new features or want to ask questions about my apps.
